name: Deploy Docs
on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gyamada619/build-docs@main
        with:
          output: docs
      - name: Inject Google Analytics Code
        run: node inject.cjs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
